spring.application.name=chemist_inventory

server.port=8008

spring.datasource.url=jdbc:mysql://localhost:3306/chemist_inventory
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
